<?php

function shift_cipher_menu() {
    $items['shift-cipher-form'] = array(
        'title' => 'Shift Cipher Form',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    $items['shift-cipher-success'] = array(
        'title' => 'Result Phrase',
        'page callback' => 'shift_cipher_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function shift_cipher_form() {
    $form['shift_value'] = array(
        '#title' => 'Shift value',
        '#type' => 'textfield',
        '#description' => t('Enter shift value: '),
        '#element_validate' => array('element_validate_integer_positive'),
        '#required' => TRUE,
    );
    $form['shift_direction'] = array(
        '#title' => 'Shift direction',
        '#type' => 'textfield',
        '#description' => t('Enter shift direction: '),
        '#element_validate' => array('element_validate_direction_word'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit',
    );

    return $form;
}
